### ISSUE TITLE
Problem with VertexArray.bind

### ISSUE THREAD

**Issue by wpk-** [cprogrammer1994/ModernGL#181]
### Issue

I think this is a bug, but I'm not clear where this happens. The below code demonstrates an incorrect result. The idea is that the input buffer contains three values per vertex, of which the shader receives a subset. The remainder is skipped by virtue of the stride. All works well when sending either 1 or all 3 values, but with 2 floats per vertex things go wonky.

Without the `vao.bind` results are as expected but (obviously) very different as it doesn't use a stride.

The test:

```python
import struct

import moderngl as gl


def test_vao_bind(array_length, loop_count, context):
    '''
    The program sums the first `count` floats for each vertex.

    For example, when `count == 3`, it sums 0 + 1 + 2 = 3 for vertex 1,
    3 + 4 + 5 = 12 for vertex 2 and 0 + 0 + 0 = 0 for vertex 3.

    The bug happens when array_length == 2 and loop_count == 2. One
    would expect the following sums:
        vertex 1: 0 + 1 = 1
        vertex 2: 3 + 4 = 7
        vertex 3: 0 + 0 = 0
    OpenGL returns 1, 6, 5 instead. I cannot see how 6 would be a sum of
    two consecutive elements.

    Args:
        array_length: Controls how many elements are passed to the GLSL
            float array `arr`. This is either 1, 2 or 3. For values < 3,
            the `stride=3*4` argument makes sure to skip the omitted
            numbers, so that vertex 2 always starts reading at 3 (index
            3) and vertex 3 always starts reading at 0 (index 6).
        loop_count: Controls how many numbers are summed. Although it is
            odd to have `loop_count > array_length`, this is not
            problematic (it will just sum the first array_length
            elements in that case).
    '''
    arr = (0, 1, 2,     # Three floats for vertex 1,
           3, 4, 5,     # vertex 2, and
           0, 0, 0)     # three zeros for vertex 3.
    buf_a = context.buffer(struct.pack('9f', *arr))
    buf_r = context.buffer(struct.pack('3f', 0, 0, 0))

    prog = context.program(
        vertex_shader='''
                #version 400
                in float[{SIZE:d}] arr;
                out float res;
                void main() {{
                    res = 0;
                    for (int i=0; i<{COUNT:d}; i++) {{
                        res += arr[i];
                    }}
                }}
            '''.format(SIZE=array_length, COUNT=loop_count),
        varyings=['res']
    )

    vao = context.vertex_array(prog, [(buf_a, '{:d}f'.format(array_length), 'arr')])
    vao.bind(prog['arr'].location, 'f', buf_a, '{:d}f'.format(array_length), offset=0, stride=3*4)
    vao.transform(buf_r, gl.POINTS, vertices=3)

    return struct.unpack('3f', buf_r.read())


if __name__ == '__main__':
    ctx = gl.create_standalone_context()
    expected_output = {
        (1, 1): (0., 3., 0.),
        (1, 2): (0., 3., 0.),
        (1, 3): (0., 3., 0.),
        (2, 1): (0., 3., 0.),
        (2, 2): (1., 7., 0.),
        (2, 3): (1., 7., 0.),
        (3, 1): (0., 3., 0.),
        (3, 2): (1., 7., 0.),
        (3, 3): (3., 12., 0.),
    }
    for (length, count), expected in expected_output.items():
        result = test_vao_bind(length, count, ctx)
        if result == expected:
            print((length, count), 'as expected.')
        else:
            print((length, count), 'expected result', expected, 'but got', result, 'instead.')
```

The output:

```
(1, 1) as expected.
(1, 2) as expected.
(1, 3) as expected.
(2, 1) as expected.
(2, 2) expected result (1.0, 7.0, 0.0) but got (1.0, 6.0, 5.0) instead.
(2, 3) expected result (1.0, 7.0, 0.0) but got (1.0, 6.0, 5.0) instead.
(3, 1) as expected.
(3, 2) as expected.
(3, 3) as expected.
```

### Version info

```
python -m moderngl
```

```
moderngl 5.0.7
--------------
vendor: Intel
renderer: Intel(R) HD Graphics 4000
version: 4.0.0 - Build 10.18.10.4885
python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
platform: win32
code: 400
```

**Comment by cprogrammer1994** [comment]
Hi!

I have run your code here are the results:

1st run (on Intel)

```
ctx.info['GL_RENDERER'] =  Intel(R) HD Graphics 630
(1, 1) as expected.
(1, 2) expected result (0.0, 3.0, 0.0) but got (0.0, 6.0, 0.0) instead.
(1, 3) expected result (0.0, 3.0, 0.0) but got (0.0, 9.0, 0.0) instead.
(2, 1) as expected.
(2, 2) expected result (1.0, 7.0, 0.0) but got (1.0, 6.0, 5.0) instead.
(2, 3) expected result (1.0, 7.0, 0.0) but got (1.0, 6.0, 5.0) instead.
(3, 1) as expected.
(3, 2) as expected.
(3, 3) as expected.
```

2nd run on nVidia

```
ctx.info['GL_RENDERER'] =  GeForce GTX 1050/PCIe/SSE2
(1, 1) as expected.
Traceback (most recent call last):
  File "examples\vao_bind_bug.py", line 75, in <module>
    result = test_vao_bind(length, count, ctx)
  File "examples\vao_bind_bug.py", line 50, in test_vao_bind
    varyings=['res']
  File "D:\Programming\ModernGL\moderngl\__init__.py", line 2883, in program
    varyings
mgl.Error: GLSL Linker failed

Program
=======
Vertex info
-----------
0(8) : error C5025: lvalue in array access too complex
0(8) : error C1068: ... or possible array index out of bounds

Link info
---------
error: Programs must have a vertex, geometry, or tessellation shader assigned to use transform Feedback varyings.
```

**Comment by cprogrammer1994** [comment]
on the second run where length = 1, count = 2
we get vetex_shader =
```glsl
#version 400
in float arr[1];
out float res;
void main() {
	res = 0;
	for (int i=0; i<2; i++) {
		res += arr[i];
	}
}
```

**Comment by wpk-** [comment]
Aw, sorry. so my demonstration code throws new errors that I didn't intend it to (based on flawed conclusions from my Intel graphics hardware).

I've reduced the test cases to the sensible ones where `loop_count <= array_length` and put it in a [gist here](https://gist.github.com/wpk-/f5d8e19f66d4f059ccb2b3e914949304). My machine still screws up on `(2, 2)`. If nVidia gives the expected result there, I suppose it's an Intel issue.

**Comment by wpk-** [comment]
Results I'm getting:

```
(1, 1) as expected.
(2, 1) as expected.
(2, 2) expected result (1.0, 7.0, 0.0) but got (1.0, 6.0, 5.0) instead.
(3, 1) as expected.
(3, 2) as expected.
(3, 3) as expected.
```

**Comment by cprogrammer1994** [comment]
VertexArray.bind works correctly. Some vertex attributes have more then one locations and those should be bound too. For example matrices and arrays can have more then 1 vertex array locations.
