### ISSUE TITLE
Testing the linux support

### ISSUE THREAD

**Issue by cprogrammer1994** [cprogrammer1994/ModernGL#43]
Test on linux using:

- PyQT4 or PyQT5
- PyGlut
- PyGame
- or any window that supports OpenGL 3.3

**Comment by stuaxo** [comment]
To clarify - eventually I guess anything in the examples dir should work ?

Currently, the only one I can launch is the QT5 example, which has a black window and the message

```
$ python QT5_01_HelloWorld.py 
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
bool QOpenGLTextureBlitter::create() Could not link shader program:
 ""
```

examples like 01_Helloworld can't import GLWindow -

```
$ python 01_HelloWorld.py 
Traceback (most recent call last):
  File "01_HelloWorld.py", line 5, in <module>
    import GLWindow as WND
ImportError: No module named 'GLWindow'
```

But I guess this is something for later, once the QT5 example works ?

**Comment by cprogrammer1994** [comment]
GLWindow is still a windows only module. Later will have linux support as well.
Unfortunately QT5 does not create an OpenGL 3.0+ context so shader creation fails.

I am currently reading about **PySide**
i have to do something like this:

```
QGLFormat glFormat;
glFormat.setVersion( 3, 3 );
```

and QT will support modern OpenGL

**Comment by cprogrammer1994** [comment]
Examples will be converted to QT5 examples for linux users.

**Comment by stuaxo** [comment]
Yup, makes sense.   I don't know QT, but I did spend much of last year playing with various OpenGL tutorials, and a lot of them had issues around this (usually trying to set the version after the GL Context was created for instance).

I did another git pull + now get to here:

```
$ python QT5_01_HelloWorld.py 
Traceback (most recent call last):
  File "QT5_01_HelloWorld.py", line 37, in initializeGL
    context['vao'] = GL.NewVertexArray(prog, vbo, '2f', ['vert'])
TypeError: NewVertexArray() argument 1 must be str, not ModernGL.Program
Aborted (core dumped)
```

**Comment by stuaxo** [comment]
Awesome, just did a ```git pull``` and now it displays a blue triangle, is this correct ?

![A Window containing a blue triangle](https://imgur.com/Wqm92e7.png)

**Comment by cprogrammer1994** [comment]
GREAT
checkout the **QT5** folder
3 is still missing
i have OpenGL 4.1 support (cannot test Raytracing, ParticleSystem)

2.2.0 is up on PyPI

**Comment by stuaxo** [comment]
Awesome, they all work for me (TM).

**Comment by cprogrammer1994** [comment]
seems to be working on ubuntu.
closing

**Comment by cprogrammer1994** [comment]
@stuaxo can I use the image above for the readme?

Can you please tell me what OS are you using?

**Comment by stuaxo** [comment]
Sure, feel free to use it.    I'm on Ubuntu 16.04 64 bit.

**Comment by shakram02** [comment]
Hello, I get this build error when trying to install the examples package, I'm not sure why the package requires `Windows.h` 3rd line from bottom to top . I'm running manjaro (arch based)

```
Installing collected packages: sip, PyQt5, GLWindow, pygame, olefile, Pillow, numpy, multipledispatch, Pyrr, ModernGL.ext.examples
  Running setup.py install for GLWindow: started
    Running setup.py install for GLWindow: finished with status 'error'
    Complete output from command /mnt/Exec/code/python/pygl_env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pycharm-packaging1/GLWindow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mne8wysa-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/Exec/code/python/pygl_env/include/site/python3.6/GLWindow:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/__main__.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/__init__.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/mock.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/keys.py -> build/lib.linux-x86_64-3.6/GLWindow
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'GLWindow.glwnd' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/mnt/Exec/code/python/pygl_env/include -I/usr/include/python3.6m -c src/GLWindow.cpp -o build/temp.linux-x86_64-3.6/src/GLWindow.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/GLWindow.cpp:4:10: fatal error: Windows.h: No such file or directory
     #include <Windows.h>
              ^~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by cprogrammer1994** [comment]
please remove `GLWindow` from the list.
Linux support for GLWindow (https://github.com/cprogrammer1994/GLWindow/issues/2) is not yet implemented.

The ModernGL examples should work with PyQt5 or pygame. This is done automatically by the ModernGL.ext.examples module.

**Comment by cprogrammer1994** [comment]
Please show me where did you find that list for pip install. I should improve the readme/docs.

**Comment by shakram02** [comment]
I'm actually now sure of how the list is made, I just ran ` pip3 install ModernGl.ext.examples `, I also don't know how to modify the list

here is the complete output if it's useful.

```
~ pip3 install ModernGl.ext.examples

Collecting ModernGl.ext.examples
  Using cached ModernGL.ext.examples-1.0.0-py3-none-any.whl
Requirement already satisfied: pygame in /usr/lib/python3.6/site-packages (from ModernGl.ext.examples)
Requirement already satisfied: Pyrr in /usr/lib/python3.6/site-packages (from ModernGl.ext.examples)
Requirement already satisfied: ModernGL in /usr/lib/python3.6/site-packages (from ModernGl.ext.examples)
Requirement already satisfied: Pillow in /usr/lib/python3.6/site-packages (from ModernGl.ext.examples)
Collecting GLWindow (from ModernGl.ext.examples)
  Using cached GLWindow-2.3.3.tar.gz
Requirement already satisfied: PyQt5 in /usr/lib/python3.6/site-packages (from ModernGl.ext.examples)
Requirement already satisfied: multipledispatch in /usr/lib/python3.6/site-packages (from Pyrr->ModernGl.ext.examples)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from Pyrr->ModernGl.ext.examples)
Requirement already satisfied: olefile in /usr/lib/python3.6/site-packages (from Pillow->ModernGl.ext.examples)
Requirement already satisfied: sip<4.20,>=4.19.3 in /usr/lib/python3.6/site-packages (from PyQt5->ModernGl.ext.examples)
Installing collected packages: GLWindow, ModernGl.ext.examples
  Running setup.py install for GLWindow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-icm2ekaa/GLWindow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o6frjgbp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/__main__.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/__init__.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/mock.py -> build/lib.linux-x86_64-3.6/GLWindow
    copying GLWindow/keys.py -> build/lib.linux-x86_64-3.6/GLWindow
    running build_ext
    building 'GLWindow.glwnd' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include/python3.6m -c src/GLWindow.cpp -o build/temp.linux-x86_64-3.6/src/GLWindow.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/GLWindow.cpp:4:10: fatal error: Windows.h: No such file or directory
     #include <Windows.h>
              ^~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-icm2ekaa/GLWindow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-o6frjgbp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-icm2ekaa/GLWindow/
```

**Comment by cprogrammer1994** [comment]
here is the setup.py of the ModernGL.ext.examples:

```
import platform
import os

PLATFORM = platform.system().lower()

if os.environ.get('READTHEDOCS') == 'True':
    from distutils.core import setup

else:
    from setuptools import setup

install_requires = ['ModernGL']

if PLATFORM == 'windows':
    if 'NO_GLWINDOW' not in os.environ:
        install_requires.append('GLWindow')

if 'NO_PYQT5' not in os.environ:
    install_requires.append('PyQt5')

if 'NO_PYGAME' not in os.environ:
    install_requires.append('pygame')

if 'NO_PYRR' not in os.environ:
    install_requires.append('Pyrr')

if 'NO_PILLOW' not in os.environ:
    install_requires.append('Pillow')

setup(
    name='ModernGL.ext.examples',
    version='1.0.0',
    author='Szabolcs Dombi',
    author_email='cprogrammer1994@gmail.com',
    description='ModernGL extension',
    url='https://github.com/cprogrammer1994/ModernGL.ext.examples',
    license='MIT',
    packages=['ModernGL.ext.examples', 'ModernGL.ext.examples.window'],
    install_requires=install_requires,
    platforms=['any'],
)
```

Can you please paste the output of the following command.

```sh
python3 -c "import platform; print(platform.system().lower())"
```

**Comment by cprogrammer1994** [comment]
no need to run the command above. I just downloaded the wheel file.

It seems the dep is added anyway:

```
    "run_requires": [
        {
            "requires": [
                "GLWindow",
                "ModernGL",
                "Pillow",
                "PyQt5",
                "Pyrr",
                "pygame"
            ]
        }
    ],
```

I will fix this bug in the next release

**Comment by cprogrammer1994** [comment]
This should work:

`pip3 install ModernGL.ext.examples -U`

**Comment by shakram02** [comment]
Worked like a charm :ok_hand: . You're really helpful, thank you so much

**Comment by kritikamehta15** [comment]
Got this while executing on Linux: 

python3 main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    ctx = ModernGL.create_context()
AttributeError: module 'ModernGL' has no attribute 'create_context'

Also, what should I do about the window, I get the same error as above.
